// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlYRJCz0o1FAlCn07ljwf7VowkTPa9fwM',
    appId: '1:865589370187:web:a40f09ccd24f90262adcce',
    messagingSenderId: '865589370187',
    projectId: 'uafc-westside-assembly',
    authDomain: 'uafc-westside-assembly.firebaseapp.com',
    storageBucket: 'uafc-westside-assembly.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1E4PTVqFgX8bsPDKty4gHlCLJczUe-RM',
    appId: '1:865589370187:android:50568e6e5740d37e2adcce',
    messagingSenderId: '865589370187',
    projectId: 'uafc-westside-assembly',
    storageBucket: 'uafc-westside-assembly.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1V7puUJmQiDiP0VfJFlnk4XJNm3dADB0',
    appId: '1:865589370187:ios:e435ffc069a84b992adcce',
    messagingSenderId: '865589370187',
    projectId: 'uafc-westside-assembly',
    storageBucket: 'uafc-westside-assembly.appspot.com',
    iosClientId: '865589370187-fnh7v8qhiebj9pb7qgjsft017hgjkd60.apps.googleusercontent.com',
    iosBundleId: 'za.org.uafcapp',
  );
}
